import "./globals.css";
import { Roboto } from "next/font/google";
import type { Metadata } from "next";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "sonner";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <CartProvider>
        <html lang="en" className={roboto.className}>
          <body className="min-h-full flex flex-col">
            <Header />
            {children}
            <Toaster
              position="top-right"
              richColors
              closeButton
              expand={true}
            />
            <Footer />
          </body>
        </html>
      </CartProvider>
    </ClerkProvider>
  );
}
